package org.ulinda.dto;

public enum SearchType {
    TEXT_CONTAINS,
    TEXT_EQUALS,
    TEXT_STARTS_WITH,
    TEXT_ENDS_WITH,
    TEXT_NOT_CONTAINS,
    TEXT_NOT_EQUALS,
    DATE_ON,
    DATE_BEFORE,
    DATE_AFTER,
    DATE_BETWEEN,
    DATE_TIME_BEFORE,
    DATE_TIME_AFTER,
    DATE_TIME_BETWEEN,
    BOOLEAN_TRUE,
    BOOLEAN_FALSE,
    DECIMAL_EQUALS,
    DECIMAL_GREATER_THAN,
    DECIMAL_LESS_THAN,
    LONG_EQUALS,
    LONG_GREATER_THAN,
    LONG_LESS_THAN
}
