package org.ulinda.exceptions;

public enum ErrorCode {
    GENERAL_ERROR,
    INTERNAL_SERVER_ERROR,
    USER_ALREADY_EXISTS,
    CONTROLLER_VALIDATION_EXCEPTION,
    VALIDATION_EXCEPTION,
    OLD_PASSWORD_INCORRECT,
    PASSWORD_REQUIREMENT_FAILED,
    USER_MUST_CHANGE_PASSWORD,
    INVALID_LOGIN_CREDENTIALS,
    ACCOUNT_LOCKED,
    RECORD_LINKED_TO_MODELS,
    MODEL_HAS_LINKED_RECORDS,
    PERMISSION_DENIED,
    SESSION_EXPIRED,
    LOGOUT_FAILED,
    UNAUTHORIZED,
    SOURCE_RECORD_MAX_LINK_COUNT_EXCEEDED,
    TARGET_RECORD_MAX_LINK_COUNT_EXCEEDED
}
